WIP - allow catalog updateLocal to ignore tip and get only stable
digitalrebar/provision pull request #568
Opened 2021-08-10 21:13 UTC by zaheena

https://github.com/rackn/product-backlog/issues/24

2021-08-10 21:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/digitalrebar/provision?pullRequest=568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/digitalrebar/provision?pullRequest=568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/digitalrebar/provision?pullRequest=568) it.</sub>

2021-08-11 13:07 UTC, galthaus commented
Looks good.  The only question is does stable imply no tip.  

I think the version flag implies that version and newer.  Tip is newer.

2021-08-11 13:12 UTC, galthaus commented
I suspect that what we really want is these patterns:
drpcli catalog updateLocal # gets all entries except tip
drpcli catalog updateLocal --version=v4.6.2  # All versions newer than v4.6.2 except tip
drpcli catalog uplodateLocal --version=stable # Stable only
drpcli catalog updateLocal --version=stable --tip # STsble + tip





8:11
Add --tip implies adding tip to all the others.
8:12
tip moves so much that this is probably reasonable.
8:12
We should proabably do this.  It is cleaner and defaults to smaller downloads.

2021-08-11 15:55 UTC, galthaus requested changes
I think the logic is incorrect in the stable case.  Please review it.

2021-08-11 15:55 UTC, galthaus commented on cli/catalog.go
> +					if v.Version != "stable" || (tip && !v.Tip) {
It thinks this needs to be:

if !(v.Version == "stable" || (tip && v.Tip))

Which is also

if v.Version != "stable" && (!tip || !v.Tip) 

Victor prefers the first form.  I prefer the more readable form.  In this case, it is the first one, I think.

2021-08-11 16:12 UTC, zaheena commented on cli/catalog.go
> +					if v.Version != "stable" || (tip && !v.Tip) {
You're right. I got lost a little here.
I think the third condition also needed to be fixed i.e only include tip if tip is set to true. Updated with a new commit.

2021-08-11 16:45 UTC, merged